version: "3"
services:
  api:
    image: bauhuynhdev/nginx-node-puppeteer
    volumes:
      - ./api:/var/www/app
      - ./api/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  web:
    image: bauhuynhdev/nginx-node-puppeteer
    volumes:
      - ./web:/var/www/app
      - ./web/vhost.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 8080
    ports:
      - 8081:80
      - 8082:8080
